

export const projects = [
    {
    technologies: [],
    _id: "123456789",
    title: "Basic-portfolio",
    image: "https://sheysathya2.netlify.app/pizzas.svg",
    description: "My portfolio website, crafted with HTML, CSS and java-script, presents a visually stunning showcase of my work and achievements. With a sleek and modern design, it delivers a seamless user experience across devices",
    link: "https://surajgupta000.github.io/Portfolio/",
    },
    {
        technologies: [],
        _id: "123456789",
        title: "Simon_Says Game",
        image: "https://sheysathya2.netlify.app/pizzas.svg",
        description: "Welcome to our Simon Says game website! Test memory and reflexes with colored sequences. Enjoy seamless gameplay on any device, compete on the leaderboard, and challenge friends. Developed with HTML, CSS, and JavaScript for endless fun!",
        link: "https://surajgupta000.github.io/Simon_Says_Game/",
        },
        {
            technologies: [],
            _id: "123456789",
            title: "Spotify_clone",
            image: "https://sheysathya2.netlify.app/pizzas.svg",
            description: "Captivating Spotify clone frontend featuring a sleek, intuitive design. Seamless navigation, vibrant UI elements, and responsive layout create an immersive music experience. Dynamic playlists, artist profiles, and a personalized home screen elevate user engagement. Modern aesthetics meet user-friendly functionality.",
            link: "https://surajgupta000.github.io/Spotify_clone-frontend/",
            },
            {
                technologies: [],
                _id: "123456789",
                title: "Tic_Tac_Toe Game",
                image: "https://sheysathya2.netlify.app/pizzas.svg",
                description: "Immerse in strategic fun with my Tic Tac Toe website! Crafted with a sleek frontend design, enjoy a seamless gaming experience. A Responsive layout ensures compatibility across devices. Dive into the nostalgia of this classic game with a modern twist",
                link: "https://surajgupta000.github.io/Tic-Tic-toe_website/",
                },
                {
                    technologies: [],
                    _id: "123456789",
                    title: "Study_Notion",
                    image: "https://sheysathya2.netlify.app/pizzas.svg",
                    description: "Study Notion is a remarkable EdTech platform, developed with modern technologies.",
                    link: "https://studynotion-frontend.vercel.app/",
                    },
                    {
                        technologies: [],
                        _id: "123456789",
                        title: "Guessing_Game",
                        image: "https://sheysathya2.netlify.app/pizzas.svg",
                        description: "This Guess the Number game challenges players to find a random number between 1-100. Each guess gives feedback: too high, too low, or invalid if out of range. Attempts are tracked, and on a correct guess, Congratulations! displays. The game auto-resets after 5 seconds for another round, encouraging improved guessing each time.",
                        link: "https://guessing-game-ashen.vercel.app/",
                        },
                        {
                            technologies: [],
                            _id: "123456789",
                            title: "Expense_Tracker",
                            image: "https://sheysathya2.netlify.app/pizzas.svg",
                            description: "Expense tracker is created using javascript's basics logic for track your expense and record it at the mean time. This project is created for learning purpose and to master javascript.",
                            link: "https://expense-tracker-seven-plum.vercel.app/",
                            },
                            {
                                technologies: [],
                                _id: "123456789",
                                title: "Timerupto_2025",
                                image: "https://sheysathya2.netlify.app/pizzas.svg",
                                description: "A timer created using Javascript for counting Number of days , Minutes and seconds remaining for 2025 year. It is just a project for learning purpose and understanding the concept of javascript.",
                                link: "https://timerupto-2025.vercel.app/",
                                },
                                {
                                    technologies: [],
                                    _id: "123456789",
                                    title: "DSA Revision_Landing_page",
                                    image: "https://sheysathya2.netlify.app/pizzas.svg",
                                    description: "",
                                    link: "https://dsa-revision-landingpage.vercel.app/",
                                    },
                                    {
                                        technologies: [],
                                        _id: "123456789",
                                        title: "HosterPage",
                                        image: "https://sheysathya2.netlify.app/pizzas.svg",
                                        description: "A hoster landing page created with tailwind css.",
                                        link: "https://hoster-landing-ten.vercel.app/",
                                        },

    
];